### PR TITLE
A11y audit

### PR DESCRIPTION
**Pull request by thomaswilburn**
- removes Modernizr
- Adds a description field to template sheets where appropriate
- Adds `role="img"` and the `aria-label` to the D3 container div
- Cleans up some property accessor code
- Adds a rule to catch extra images without alt text

### CODE REVIEW

**Comment by alykat** [comment]
Quick thoughts:

- Thanks for taking a look at this. I think the approach you suggest makes a lot of sense for our everyday graphics. And we can look at accessibility options for more complex projects as needed / as we go.

- In the template spreadsheet, maybe we should make the `description` label more explicit about its purpose. `aria-description`?

- Also in the template spreadsheet, I think I'd feel better if we moved the prompt to the third column, rather than having it pull into the page as a default. I can see it slipping through the cracks and winding up on published pages, unedited. Or is there some other way to remind designers/devs to fill it in? A console warning on localhost/127.0.0.1 if that field is empty?

- The rendered description probably needs to be escaped somehow? For example, on the bar chart template, note the double quotes in the description:

```
aria-label="This is a description of the graphic for accessibility purposes (users running a screen reader). If the subhed is sufficiently descriptive of what the graphic shows, you can leave this blank. Otherwise, please fill in a short narrative description of what the graphic shows (e.g., "A bar chart showing a 200% increase in grain futures for the last three years")."
```

- Removing modernizr also makes sense.

- I'm a little leery about removing underscore — mostly b/c I find underscore functions a lot easier to read/understand than `map`. But I also see the appeal of removing another helper library and dropping some file weight.

- Let's talk about the other JS style changes, particularly the switch to dot notation. This team has historically preferred bracket notation [as a matter of style](https://github.com/nprapps/bestpractices/blob/master/javascript.md). And while I'm definitely game for revisiting our team coding best practices, I'm going to take a stand for bracket notation b/c 1) it makes more explicit what's data and what's a property; and 2) it's a little more flexible, allowing for passing in variables and addressing data columns that have spaces in the name.

**Comment by thomaswilburn** [comment]
Sure, I can move the prompt to the third column. `description` seemed like it would be understandable by copy-edit staff in a way that `a11y_description` wouldn't be, but I'm up for either one. It definitely does need to be escaped, good catch.

Underscore isn't a huge dependency, but my hope would be that using the standard library (including Array.map, Array.forEach, etc.) is easier to onboard people and also dovetails more easily with ES2015 collection features like Map, Set, arrow functions, etc.

I don't really understand what you mean by "data vs. property," and would like to hear more. Bracket notation seems appropriate to me when dynamically selecting properties or using odd property names, as you noted, but otherwise it's not very idiomatic for JavaScript, and it may make some tooling advancements (like tree-shaking or type-checking) harder to use.

**Comment by thomaswilburn** [comment]
Also, I'd really like to merge the Drive branch before this one, if possible. It's frustrating to have to make template sheet changes in two places each time.

**Comment by alykat** [comment]
Now that I've merged in the `drive` branch, the template spreadsheet IDs have changed. I think there are changes that may have been made to the original set of template spreadsheets (for example, renaming `description` to `screenreader`) that didn't make it over to the new template spreadsheets.

**Comment by thomaswilburn** [comment]
I'll double-check, but I think I made the `screenreader` change to both. If anything, I'm more worried that I missed the originals--the organized templates are easier to find.

**Comment by alykat** [comment]
Ah, false alarm. I was testing this but hadn't merged in the post-`drive` version of `master`.

**Pull request merged**
